### ISSUE TITLE
[Feature Request] Add Intel WiFi Driver Instructions 

### ISSUE THREAD

**Issue by reece394** [gorquan/OC-XPS-7590#10]
Now that AirPortItlwm exists [here](https://github.com/OpenIntelWireless/itlwm) You should add instructions for users who do not wish to use Broadcom WiFi cards. It is in Beta and the according to FAQ the WiFi speeds are not the same as Broadcom ATM but will suit people who have so far been relying on USB WiFi Dongles. Awesome work on this so far!

**Comment by gorquan** [comment]
I can add instructions in the Readme file, but the related kexts will not be merged into the warehouse
