### ISSUE TITLE
带触屏的机型Kernel_Task CPU 占用率异常

### ISSUE THREAD

**Issue by ygjsz** [gorquan/OC-XPS-7590#14]
如题，在带触屏的机型上系统空闲时Kernel_Task会占用50-60%的CPU，导致了续航下降严重，在BIOS禁用触摸屏之后问题解决，希望能加入一个禁用触摸屏的SSDT供大家选用。
系统为版本为10.15.7
补充：虽然禁用了触屏之后Kernel_Task占用CPU的问题解决了，但是睡眠唤醒之后Kernel_Task又会重新占50-60%的CPU，比较难受

**Comment by gorquan** [comment]
大哥，你是来搞笑的吗？我自己用的非触摸，README已经写得清清楚楚1080p非触摸，你还要我提供禁用触摸SSDT。当然你提供一台触摸的XPS 15给我，别说加入禁用触摸屏SSDT，开个仓库给你都可以。
