### ISSUE TITLE
关于type-c接口不能正常识别硬盘问题

### ISSUE THREAD

**Issue by HBUer** [gorquan/OC-XPS-7590#18]
我的型号是i5 9300H的1080p，系统是11.01
![截屏2020-11-25 19 27 18](https://user-images.githubusercontent.com/66448191/100222490-21291c00-2f55-11eb-8e65-9d9aca668a43.png)
如上图：只有开机前，插上外置type-c转sata，开机后才能识别硬盘。但是不能在hackintool里面找到设备。
同时，在开机后拔插硬盘，均不能被识别。
![截屏2020-11-25 19 30 09](https://user-images.githubusercontent.com/66448191/100222885-b0ceca80-2f55-11eb-92cd-35764dee08ea.png)

**Comment by gorquan** [comment]
我也没有这台机器，你教一下我怎么云排错？

**Comment by HBUer** [comment]
不知道是啥原因，更新了最新版的bios，竟然正常了
