### ISSUE TITLE
0.5.9 应该使用哪个版本的OCC来编辑plist呢？

### ISSUE THREAD

**Issue by illusion899** [gorquan/OC-XPS-7590#2]
大佬好，用了您的efi成功安装，因为想使用iMessage需要改一下config.plist，但是试用了2.6.0和2.5.0的OCC改变plist之后再引导时都出现了问题（图是2.5.0改plist之后，用2.6.0改plist之后会只显示no vault那行），请问应该用哪个版本的OCC来改plist呢？ 
![IMG_20200614_134717](https://user-images.githubusercontent.com/66808454/84601900-3435ad00-ae49-11ea-9ab0-e467160cd864.jpg)

**Comment by Dracay** [comment]
用2.6.0.2，不要用2.6.0.1这个0.1有BUG
2.6.0和2.5.0都不兼容  最好是用ProperTree

**Comment by illusion899** [comment]
好的，我马上试一下，之前因为使用2.6.0和2.5.0把opencore玩儿崩了，正在准备重新装系统。。。。
还有几个问题想请教，第一是之前opencore启动在windows和mac之前会显示一个no name 的选项，请问有办法把它去掉吗（因为现在对改config有阴影。。）？第二个是使用这个efi安装之后还需要洗白才能使用imessage 还是直接就能使用呢？第三个是之前有时候启动会导致触摸板无法被检测到，是不是有个sudo 开头的命令行能激活voodoops2controller来着？ TIA  感谢

**Comment by gorquan** [comment]
0.5.9直接用2.6.0.2就行了，我这个配置最新版本会一直更新的，以后直接用最新的OCC来编辑就可以。

**Comment by gorquan** [comment]
我的配置会随着OC更新而更新的，所以直接用2.6.0.2就ok，以后的话直接用最新版的OCC。洗白这个问题我没搞，你好了

**Comment by gorquan** [comment]
我的配置会随着OC更新而更新的，所以直接用2.6.0.2就ok，以后的话直接用最新版的OCC。当然，我建议你用ProperTree或者VS Code进行小修改然后用OCC来检测有没有问题。
no name的话你检查下你是不是存在其他EFI引导，我这边直接是显示Windows和MacOS
洗白这个问题我没有去搞，咸鱼有卖白果三码洗白的，你可以试试。当然如果你用我这个还能洗白了也告诉我一下哈
触摸板问题应该是解决的了，我这边没有出过问题。最近出了新的驱动，我暂时还没有去更新他，你可以试试。

**Comment by Dracay** [comment]
2.4.3已解决了触摸板的问题 可以更新了

**Comment by illusion899** [comment]
> 我的配置会随着OC更新而更新的，所以直接用2.6.0.2就ok，以后的话直接用最新版的OCC。当然，我建议你用ProperTree或者VS Code进行小修改然后用OCC来检测有没有问题。
> no name的话你检查下你是不是存在其他EFI引导，我这边直接是显示Windows和MacOS
> 洗白这个问题我没有去搞，咸鱼有卖白果三码洗白的，你可以试试。当然如果你用我这个还能洗白了也告诉我一下哈
> 触摸板问题应该是解决的了，我这边没有出过问题。最近出了新的驱动，我暂时还没有去更新他，你可以试试。

我又重新从头装了一遍，这次触摸板的问题得到了解决。**三码的问题我并没有用OCC做修改，直接登录了appleiD成功，并且imessage 和 facetime都可以正常使用，但是我不知道是否是上次做修改的原因**
两个新问题：第一个是如何更新kext呢？是否直接放在EFI文件夹里就可以呢？
第二个问题是用opencore引导的时候，如果将ShowPicker选为no，什么快捷键能调出这个show picker呢（我测试了Esc和Alt单独按都没反应）？

**Comment by gorquan** [comment]
羡慕了，可以分享下洗白教程吗
1. 更新Kext直接复制到Kexts文件夹下面，如果原来有这个Kext的话，不用更新Config; 如果没有就用OCC或者手动添加一下Kext信息到Config里面。
2. 这个问题我没有去尝试，你可以看看论坛或者海外友人有没有处理这个问题

**Comment by illusion899** [comment]
> 羡慕了，可以分享下洗白教程吗
> 
> 1. 更新Kext直接复制到Kexts文件夹下面，如果原来有这个Kext的话，不用更新Config; 如果没有就用OCC或者手动添加一下Kext信息到Config里面。
> 2. 这个问题我没有去尝试，你可以看看论坛或者海外友人有没有处理这个问题

您客气，本来就是从您这伸手来的。。。 
我洗白应该是参考了这个教程_**https://shuiyunxc.gitee.io/2020/03/16/Three/index/**_
重装之后实际上我没有再操作，因为上次改plist把系统搞崩了，有点后怕。我觉得可能性有两个
1.上次三码之后在硬盘留某处下信息，导致这次不用重新编辑就可以（但是整个盘是格式化过的，不知道可能性大不大）
2.本来直接登陆就可以，EFI里面已经含有洗白的三码
因为我不太懂这个，就没再敢尝试，您可以控制变量试一下

**Comment by gorquan** [comment]
ok，我有空试试，谢谢啦

**Comment by gorquan** [comment]
> > 羡慕了，可以分享下洗白教程吗
> > 
> > 1. 更新Kext直接复制到Kexts文件夹下面，如果原来有这个Kext的话，不用更新Config; 如果没有就用OCC或者手动添加一下Kext信息到Config里面。
> > 2. 这个问题我没有去尝试，你可以看看论坛或者海外友人有没有处理这个问题
> 
> 您客气，本来就是从您这伸手来的。。。
> 我洗白应该是参考了这个教程_**https://shuiyunxc.gitee.io/2020/03/16/Three/index/**_
> 重装之后实际上我没有再操作，因为上次改plist把系统搞崩了，有点后怕。我觉得可能性有两个
> 1.上次三码之后在硬盘留某处下信息，导致这次不用重新编辑就可以（但是整个盘是格式化过的，不知道可能性大不大）
> 2.本来直接登陆就可以，EFI里面已经含有洗白的三码
> 因为我不太懂这个，就没再敢尝试，您可以控制变量试一下

我知道了，EFI的配置已经洗白了的，是我的号被Apple拉黑了，无解了

**Comment by illusion899** [comment]
> > > 羡慕了，可以分享下洗白教程吗
> > > 
> > > 1. 更新Kext直接复制到Kexts文件夹下面，如果原来有这个Kext的话，不用更新Config; 如果没有就用OCC或者手动添加一下Kext信息到Config里面。
> > > 2. 这个问题我没有去尝试，你可以看看论坛或者海外友人有没有处理这个问题
> > 
> > 
> > 您客气，本来就是从您这伸手来的。。。
> > 我洗白应该是参考了这个教程_**https://shuiyunxc.gitee.io/2020/03/16/Three/index/**_
> > 重装之后实际上我没有再操作，因为上次改plist把系统搞崩了，有点后怕。我觉得可能性有两个
> > 1.上次三码之后在硬盘留某处下信息，导致这次不用重新编辑就可以（但是整个盘是格式化过的，不知道可能性大不大）
> > 2.本来直接登陆就可以，EFI里面已经含有洗白的三码
> > 因为我不太懂这个，就没再敢尝试，您可以控制变量试一下
> 
> 我知道了，EFI的配置已经洗白了的，是我的号被Apple拉黑了，无解了

。。。。节哀。。再请教一下，如果用黑苹果登录ApppleID的话会被拉黑吗? 我在网上没找到具体的说法

**Comment by gorquan** [comment]
> > > > 羡慕了，可以分享下洗白教程吗
> > > > 
> > > > 1. 更新Kext直接复制到Kexts文件夹下面，如果原来有这个Kext的话，不用更新Config; 如果没有就用OCC或者手动添加一下Kext信息到Config里面。
> > > > 2. 这个问题我没有去尝试，你可以看看论坛或者海外友人有没有处理这个问题
> > > 
> > > 
> > > 您客气，本来就是从您这伸手来的。。。
> > > 我洗白应该是参考了这个教程_**https://shuiyunxc.gitee.io/2020/03/16/Three/index/**_
> > > 重装之后实际上我没有再操作，因为上次改plist把系统搞崩了，有点后怕。我觉得可能性有两个
> > > 1.上次三码之后在硬盘留某处下信息，导致这次不用重新编辑就可以（但是整个盘是格式化过的，不知道可能性大不大）
> > > 2.本来直接登陆就可以，EFI里面已经含有洗白的三码
> > > 因为我不太懂这个，就没再敢尝试，您可以控制变量试一下
> > 
> > 
> > 我知道了，EFI的配置已经洗白了的，是我的号被Apple拉黑了，无解了
> 
> 。。。。节哀。。再请教一下，如果用黑苹果登录ApppleID的话会被拉黑吗? 我在网上没找到具体的说法

我觉得应该是看人品，今天我洗白了重新登录个号又被拉黑，就iMessage和FaceTime不能用，其他都正常。
有的人又可以正常使用。

**Comment by illusion899** [comment]
新问题。。。
在睡眠后（较长时间）再唤醒，耳机无法正常发声而是高频噪音，在短暂睡眠后不会出现这个问题（电脑扬声器和蓝牙耳机都没出现这个问题，只有有线耳机），请问大概有什么可能的解决方案吗？

**Comment by gorquan** [comment]
> 新问题。。。
> 在睡眠后（较长时间）再唤醒，耳机无法正常发声而是高频噪音，在短暂睡眠后不会出现这个问题（电脑扬声器和蓝牙耳机都没出现这个问题，只有有线耳机），请问大概有什么可能的解决方案吗？

是的，我已经发现这个问题了，但是我暂时还没时间去解决这个问题，后面我解决了会更新过来

**Comment by illusion899** [comment]
> > 新问题。。。
> > 在睡眠后（较长时间）再唤醒，耳机无法正常发声而是高频噪音，在短暂睡眠后不会出现这个问题（电脑扬声器和蓝牙耳机都没出现这个问题，只有有线耳机），请问大概有什么可能的解决方案吗？
> 
> 是的，我已经发现这个问题了，但是我暂时还没时间去解决这个问题，后面我解决了会更新过来

得嘞，那坐等伸手了，感谢！

**Comment by illusion899** [comment]
又来了大佬。。。 几个问题想请教
1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
3）这个耳机爆音是会不会比上个版本更稳定一些
以上，谢谢！

**Comment by gorquan** [comment]
> 又来了大佬。。。 几个问题想请教
> 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> 3）这个耳机爆音是会不会比上个版本更稳定一些
> 以上，谢谢！

1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别

**Comment by illusion899** [comment]
> > 又来了大佬。。。 几个问题想请教
> > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > 以上，谢谢！
> 
> 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别

谢谢大佬，我马上试一下，再次感谢！

**Comment by gorquan** [comment]
> > > 又来了大佬。。。 几个问题想请教
> > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > 以上，谢谢！
> > 
> > 
> > 
> > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> 
> 谢谢大佬，我马上试一下，再次感谢！

小事，有问题随时提ISSUE，我看到就会回复

**Comment by illusion899** [comment]
> > > > 又来了大佬。。。 几个问题想请教
> > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > 以上，谢谢！
> > > 
> > > 
> > > 
> > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > 
> > 
> > 谢谢大佬，我马上试一下，再次感谢！
> 
> 小事，有问题随时提ISSUE，我看到就会回复

/:@)/:@)/:@)/:@)

**Comment by illusion899** [comment]
> > > > 又来了大佬。。。 几个问题想请教
> > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > 以上，谢谢！
> > > 
> > > 
> > > 
> > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > 
> > 
> > 谢谢大佬，我马上试一下，再次感谢！
> 
> 小事，有问题随时提ISSUE，我看到就会回复

本来想发拱手的emoji。。。。失败了。。
拱手*4
打扰了

**Comment by illusion899** [comment]
> > > > > 又来了大佬。。。 几个问题想请教
> > > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > > 以上，谢谢！
> > > > 
> > > > 
> > > > 
> > > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > > 
> > > 
> > > 谢谢大佬，我马上试一下，再次感谢！
> > 
> > 
> > 小事，有问题随时提ISSUE，我看到就会回复
> 
> 本来想发拱手的emoji。。。。失败了。。
> 拱手*4
> 打扰了

大佬，0.6.0已经升级完成，耳机的问题还是存在。。。。
根据我的感受是在通电的情况下睡眠模式比较久会出现，但是在刚刚拔掉电源后即使一直在耳机播放音频也会在30s-120s内出现静音，然后就是高频噪音，希望这个观察对解决问题有帮助，辛苦啦！！

题外话，您知道oc设置为不显示启动菜单后什么快捷键能唤出菜单吗？ESC，windows和Fn都快被摁烂了。。。。

**Comment by gorquan** [comment]
> > > > > > 又来了大佬。。。 几个问题想请教
> > > > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > > > 以上，谢谢！
> > > > > 
> > > > > 
> > > > > 
> > > > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > > > 
> > > > 
> > > > 谢谢大佬，我马上试一下，再次感谢！
> > > 
> > > 
> > > 小事，有问题随时提ISSUE，我看到就会回复
> > 
> > 
> > 本来想发拱手的emoji。。。。失败了。。
> > 拱手*4
> > 打扰了
> 
> 大佬，0.6.0已经升级完成，耳机的问题还是存在。。。。
> 根据我的感受是在通电的情况下睡眠模式比较久会出现，但是在刚刚拔掉电源后即使一直在耳机播放音频也会在30s-120s内出现静音，然后就是高频噪音，希望这个观察对解决问题有帮助，辛苦啦！！
> 
> 题外话，您知道oc设置为不显示启动菜单后什么快捷键能唤出菜单吗？ESC，windows和Fn都快被摁烂了。。。。

升级0.6.0应该没什么问题吧，还多了个风扇控制，我觉得美滋滋的
耳机这个的确是，我继续排查一下吧，要是出现这种问题你重启一下
唤出菜单这个我记得小兵的那个OC文档有写，不过我忘了，我待会找到了发在这里

**Comment by illusion899** [comment]
> > > > > > > 又来了大佬。。。 几个问题想请教
> > > > > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > > > > 以上，谢谢！
> > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > > > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > > > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > > > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > > > > 
> > > > > 
> > > > > 谢谢大佬，我马上试一下，再次感谢！
> > > > 
> > > > 
> > > > 小事，有问题随时提ISSUE，我看到就会回复
> > > 
> > > 
> > > 本来想发拱手的emoji。。。。失败了。。
> > > 拱手*4
> > > 打扰了
> > 
> > 
> > 大佬，0.6.0已经升级完成，耳机的问题还是存在。。。。
> > 根据我的感受是在通电的情况下睡眠模式比较久会出现，但是在刚刚拔掉电源后即使一直在耳机播放音频也会在30s-120s内出现静音，然后就是高频噪音，希望这个观察对解决问题有帮助，辛苦啦！！
> > 题外话，您知道oc设置为不显示启动菜单后什么快捷键能唤出菜单吗？ESC，windows和Fn都快被摁烂了。。。。
> 
> 升级0.6.0应该没什么问题吧，还多了个风扇控制，我觉得美滋滋的
> 耳机这个的确是，我继续排查一下吧，要是出现这种问题你重启一下
> 唤出菜单这个我记得小兵的那个OC文档有写，不过我忘了，我待会找到了发在这里

那太好了，非常感谢！抱歉没意识到风扇加强了，失礼失礼

**Comment by gorquan** [comment]
> > > > > > > > 又来了大佬。。。 几个问题想请教
> > > > > > > > 1）最近fn+声音/亮度调节失灵，是否能通过改变OC引导修复
> > > > > > > > 2）在更换引导后（boot文件夹替换后）还能引导到原来的Mac系统吗（之前的设置和软件还能不能用）
> > > > > > > > 3）这个耳机爆音是会不会比上个版本更稳定一些
> > > > > > > > 以上，谢谢！
> > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > 1. Fn+音量/亮度失灵，是因为驱动的问题，你更新Kexts就好（主要是Voodoo*），我这边暂时没有遇到这个
> > > > > > > 2. 更换引导是可以引导原来的MacOS的，无论你是直接升级Opencore还是Opencore和Clover互换，两种情况我都试过了，Opencore只要保证有ApfsDriverLoader.efi这个Drivers就可以识别MacOS，Opencore只要不改动序列号方面的信息的话一些激活的软件不会丢激活，
> > > > > > > 3. 说一下耳机爆音这个问题的进度：大概的原因我有了一个把握，也知道修复一个方向，不过我还在考虑要不要修复，你先升级看看还会不会遇到吧（主要是比较难复现）
> > > > > > > 4. 注意要看Readme，DW1560最新的Brcm驱动没办法识别
> > > > > > 
> > > > > > 
> > > > > > 谢谢大佬，我马上试一下，再次感谢！
> > > > > 
> > > > > 
> > > > > 小事，有问题随时提ISSUE，我看到就会回复
> > > > 
> > > > 
> > > > 本来想发拱手的emoji。。。。失败了。。
> > > > 拱手*4
> > > > 打扰了
> > > 
> > > 
> > > 大佬，0.6.0已经升级完成，耳机的问题还是存在。。。。
> > > 根据我的感受是在通电的情况下睡眠模式比较久会出现，但是在刚刚拔掉电源后即使一直在耳机播放音频也会在30s-120s内出现静音，然后就是高频噪音，希望这个观察对解决问题有帮助，辛苦啦！！
> > > 题外话，您知道oc设置为不显示启动菜单后什么快捷键能唤出菜单吗？ESC，windows和Fn都快被摁烂了。。。。
> > 
> > 
> > 升级0.6.0应该没什么问题吧，还多了个风扇控制，我觉得美滋滋的
> > 耳机这个的确是，我继续排查一下吧，要是出现这种问题你重启一下
> > 唤出菜单这个我记得小兵的那个OC文档有写，不过我忘了，我待会找到了发在这里
> 
> 那太好了，非常感谢！抱歉没意识到风扇加强了，失礼失礼

方便的话，你可以加一下我的QQ，什么时候我修好了这个耳机问题你帮我测试下，我这边比较完美懒得动环境了
