### ISSUE TITLE
关于亮度加载缓慢问题

### ISSUE THREAD

**Issue by wxxsfxyzm** [gorquan/OC-XPS-7590#21]
本人经试验已经找到解决方法，将Whatevergreen.kext降级至1.4.5版本不要升级，这是最适合UHD630的版本，高了就会出bug

**Comment by gorquan** [comment]
> 本人经试验已经找到解决方法，将Whatevergreen.kext降级至1.4.5版本不要升级，这是最适合UHD630的版本，高了就会出bug

感谢，可以试试，但不是长久之计

**Comment by gorquan** [comment]
目前版本已经修复
