### ISSUE TITLE
关于BIOS设置问题

### ISSUE THREAD

**Issue by flyingchase** [gorquan/OC-XPS-7590#22]
请问博主的bios版本和设置是怎样的啊? 能在readme.md更新一下吗? 我在您efi基础上修改为4k版本的安装遇到AppleActuatorDeviceUserClient::start Entered问题, 外接显示器可以进入安装界面但十几秒后自动重启.

**Comment by gorquan** [comment]
其实就是那个文章。。我写在readme了。。
况且 我这是1080p，你问我4k啥情况我也不知道。。

**Comment by flyingchase** [comment]
你好！不好意思再来打扰一下，请问您 7590 的 BIOS 版本是多少啊？ 我的是 1.7.0 在某些场景下经常出现降频到0.78ghz，尝试过散热改造和voltageShift降压，效果不明显。 在 dell 官网发现 bios 更新记录里面显示有一版本 bios 修复了 type-c供电相关的问题，想更新 bios 试试看。

**Comment by oreoft** [comment]
> 你好！不好意思再来打扰一下，请问您 7590 的 BIOS 版本是多少啊？ 我的是 1.7.0 在某些场景下经常出现降频到0.78ghz，尝试过散热改造和voltageShift降压，效果不明显。 在 dell 官网发现 bios 更新记录里面显示有一版本 bios 修复了 type-c供电相关的问题，想更新 bios 试试看。

我的测试结果是和bios没关系，和pch和rvm的散热关系大一些。

**Comment by gorquan** [comment]
> 你好！不好意思再来打扰一下，请问您 7590 的 BIOS 版本是多少啊？ 我的是 1.7.0 在某些场景下经常出现降频到0.78ghz，尝试过散热改造和voltageShift降压，效果不明显。 在 dell 官网发现 bios 更新记录里面显示有一版本 bios 修复了 type-c供电相关的问题，想更新 bios 试试看。

我好像也是1.7.0，反正没更新过，这个和bios不一定有关系，某些情景也看你什么情景，你像CPU满载了降频到800Mhz正常啊，不然直接爆炸了，白果也一样，CPU满负载的情况下都会降频自我保护

**Comment by flyingchase** [comment]
> > 你好！不好意思再来打扰一下，请问您 7590 的 BIOS 版本是多少啊？ 我的是 1.7.0 在某些场景下经常出现降频到0.78ghz，尝试过散热改造和voltageShift降压，效果不明显。 在 dell 官网发现 bios 更新记录里面显示有一版本 bios 修复了 type-c供电相关的问题，想更新 bios 试试看。
> 
> 我好像也是1.7.0，反正没更新过，这个和bios不一定有关系，某些情景也看你什么情景，你像CPU满载了降频到800Mhz正常啊，不然直接爆炸了，白果也一样，CPU满负载的情况下都会降频自我保护

我这通常编译时常常出现，打开两个idea 窗口，Type-c /hdmi外接 4k 屏幕打开几个网页就会大概率出现锁频到 0.8ghz，这时候 cpu和 gpu温度才 60，风扇都没怎么转。。。改造 VRM 散热贴，更换硅脂都试了，给 cpu/gpu 降压也没明显效果，都怀疑是主板硬件传感器损坏了。。。

**Comment by gorquan** [comment]
> > > 你好！不好意思再来打扰一下，请问您 7590 的 BIOS 版本是多少啊？ 我的是 1.7.0 在某些场景下经常出现降频到0.78ghz，尝试过散热改造和voltageShift降压，效果不明显。 在 dell 官网发现 bios 更新记录里面显示有一版本 bios 修复了 type-c供电相关的问题，想更新 bios 试试看。
> > 
> > 
> > 我好像也是1.7.0，反正没更新过，这个和bios不一定有关系，某些情景也看你什么情景，你像CPU满载了降频到800Mhz正常啊，不然直接爆炸了，白果也一样，CPU满负载的情况下都会降频自我保护
> 
> 我这通常编译时常常出现，打开两个idea 窗口，Type-c /hdmi外接 4k 屏幕打开几个网页就会大概率出现锁频到 0.8ghz，这时候 cpu和 gpu温度才 60，风扇都没怎么转。。。改造 VRM 散热贴，更换硅脂都试了，给 cpu/gpu 降压也没明显效果，都怀疑是主板硬件传感器损坏了。。。

编译的时候出现 很正常 我目前开两个Windows虚拟机也会出现这种情况
