### ISSUE TITLE
4K Screen problem waking from sleep

### ISSUE THREAD

**Issue by romancin** [gorquan/OC-XPS-7590#3]
Hi! Thank you very much for your work. It has been the best I have seen and I tried a lot :)

The only problem I have is that when I close and open the lid, the screen is completely unusable:
![69070F87-6784-4564-9FF7-FEB09B87B516](https://user-images.githubusercontent.com/17579835/86529488-4d160900-beb1-11ea-94b4-7411833f4dbf.jpeg)

Do you know how I can try to fix it? Thank you!

**Comment by gorquan** [comment]
sorry，My version is 1080p. This seems to be due to a problem with the 4K display, there is no solution for the time being.If you have any good solutions, please let me know

**Comment by romancin** [comment]
> sorry，My version is 1080p. This seems to be due to a problem with the 4K display, there is no solution for the time being.If you have any good solutions, please let me know

Found it, works perfectly with your EFI folder making only 2 changes in config.plist:
```
<key>NVRAM</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14</key>
			<dict>
				<key>UIScale</key>
				<data>Ag==</data>
			</dict>
...
```
and
```
<key>DeviceProperties</key>
	<dict>
		<key>Add</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x2,0x0)</key>
			<dict>
				<key>dpcd-max-link-rate</key>
				<data>FAAAAA==</data>
```
It would be awesome if you can include this in the README :)

Thank you for your work!!
