### ISSUE TITLE
Black Screen - Wake from sleep - OLED MODEL - XPS 7590

### ISSUE THREAD

**Issue by CryptoNeverSleeps** [gorquan/OC-XPS-7590#5]
I need some help fixing Wake from Sleep.. Black Screen with OLED version of 7590...

You 2 have the most success for this model... your help would be greatly appreciated. Using both of your latest 7590 - OpenCore releases... OLED.. no matter if it's Clover or OpenCore... wake to Black screen.. I can TeamViewer in the machine so I know sleep and Lid patch are working ...this is only happening on OLED... my DSDT dump is on my Github....

Thanks again to you both for contributions..

**Comment by gorquan** [comment]
What is the problem, can you describe it in detail? Is the system unable to sleep or cannot wake up from sleep or wake up with a black screen?

**Comment by CryptoNeverSleeps** [comment]
Maybe this might help.....

https://www.reddit.com/r/hackintosh/comments/f3mqx9/xps_7590_oled_screen_dark_after_screen_off/

**Comment by CryptoNeverSleeps** [comment]
The laptop seems to sleep and wake fine.... the problem is on the XPS 7590 OLED Model .........the screen remains black... I can TeamViewer into the machine... so I know it's running and nothing has locked up.... However the screen remains black... Not sure if it's a ACPI issue... something is not telling the screen to power back on..........The PC itself resumes.... The screen remains black.

**Comment by gorquan** [comment]
@CryptoNeverSleeps I'm sorry, I may have time to try to fix it for you on weekends, is that okay?

**Comment by CryptoNeverSleeps** [comment]
That's perfectly fine... I'm even willing to pay lol.........

Appreciate all your help.   If you need to contact me.... Email me direct or reply to this issue....

Thanks again for all your work...  I just emailed you my contact info also.

**Comment by gorquan** [comment]
@CryptoNeverSleeps Okok

**Comment by CryptoNeverSleeps** [comment]
Any Luck?

**Comment by gorquan** [comment]
@CryptoNeverSleeps I'm sorry, because business is busy during this time, and I also work on weekends, so I have less time to deal with these problems. So I’m still investigating, there should be a big progress during the National Day holiday in October

**Comment by Jialin-Wu** [comment]
@gorquan I met the same problem - build-in screen become BLACK after sleeping wake up in my laptop MacOS 10.15.7. My laptop is Dell XPS15 7590 - 4K OLED - Coffee Lake 9750 + 1T NVME Plextor SSD + DW 1820A + 2 x 8G DDR4 Mem. Would you pls. post the update if you have? Thanks a lot.

**Comment by CryptoNeverSleeps** [comment]
1080P and 4K Touch Models of the 7590 Work with no problem at all... Our issue is 100% related to the OLED Screen.

**Comment by xfw100** [comment]
等待两位大佬更新oc，解决休眠无法唤醒，还有OLED无法安装bigsur

**Comment by CryptoNeverSleeps** [comment]
I'll attempt Big Sur next weekend.

**Comment by CryptoNeverSleeps** [comment]
Once the OLED Sleep issue is fixed this will be a beast of a Laptop....

| Key                    | Value                                                        |
| ---------------------- | ------------------------------------------------------------ |
| SKU                    | [XPS-7590 Notebook PC]                                       |
| CPU                    | Intel Core i7 9750H                                          |
| GPU                    | Intel Graphics UHD 630 + NVIDIA GTX 1650 (4GB)               |
| Built-In Screen        | 15.6"  4K OLED ( Samsung SDCA029 )                           |
| RAM                    | Vengeance® Series 64GB (2 x 32GB) DDR4 SODIMM 2666MHz        |
| Internal SSD - Windows | Samsung 970 PRO NVMe M.2 SSD 1TB -                           |
| External SSD - macOS   | PC611 NVMe SK Hynix 512GB + Sabrent Rocket Pro NVMe Enclosure|
| Audio                  | Realtek ALC298                                               |
| Wireless               | Dell Wireless DW1820A                                        |
| ---------------------- | ------------------------------------------------------------ |

**Comment by xfw100** [comment]
bigsur对4K屏幕支持不友好，需要改48hz刷新率，但是OLED屏幕更改后（44hz），依旧无法点亮屏幕，不知道是否需要改到更低刷新率，期待你成功！

**Comment by CryptoNeverSleeps** [comment]
On 0.6.2 Version - 10.15.7 - Immediate Black screen After Apple Logo progress bar and screen flicker...  Caps Lock Key responds..... I know the system is on...... I can even see my system online via TeamViewer but was unable to make a connection...

**Comment by gorquan** [comment]
> On 0.6.2 Version - 10.15.7 - Immediate Black screen After Apple Logo progress bar and screen flicker... Caps Lock Key responds..... I know the system is on...... I can even see my system online via TeamViewer but was unable to make a connection...

I think OLED controller not working，but I havent device to fix and test it.

**Comment by gorquan** [comment]
> On 0.6.2 Version - 10.15.7 - Immediate Black screen After Apple Logo progress bar and screen flicker... Caps Lock Key responds..... I know the system is on...... I can even see my system online via TeamViewer but was unable to make a connection...

In 1080p version device, no problem

**Comment by CryptoNeverSleeps** [comment]
Hmmm...... Contact me via email...... I think you have my personal...

**Comment by xfw100** [comment]
可以参考下4k外接OLED屏幕，刷新率是在4k@30hz，我用gorquanwu的efi是可以安装bigsur的，但是屏幕无法点亮，可以键盘输入的声音。

**Comment by CryptoNeverSleeps** [comment]
I'll look into this when I get a chance... Approaching my max level of expertise......

https://www.reddit.com/r/hackintosh/comments/c0sm7f/black_screen_after_refresh_rate_change/

**Comment by CryptoNeverSleeps** [comment]
Does this help?

https://github.com/CryptoNeverSleeps/DELL-XPS-7590-OLED/blob/master/DSDT/DSDT-Power-Resources-for-Wake.txt

**Comment by CryptoNeverSleeps** [comment]
External (_SB_.PCI0.GFX0.LCD_.BBRD, MethodObj)    // 2 Arguments
    External (_SB_.PCI0.GFX0.LCD_.OIDE, MethodObj)    // 0 Arguments

**Comment by CryptoNeverSleeps** [comment]
Not giving up on OLED screen's reaching my max capability.... This is the latest research I have come across....

Actually can you dump your EDID using Darwin Dumper and attach the Desktop Folder results.... Thanks...

https://www.tonymacx86.com/threads/solved-black-screen-after-upgrade-to-high-sierra.237050/page-5

https://embdev.net/topic/284710
