### ISSUE TITLE
MacOS Big Sur Wakeup issues

### ISSUE THREAD

**Issue by wxxsfxyzm** [gorquan/OC-XPS-7590#6]
Thank you for the great work of OC 0.6! And I use it to boot MacOS big sur and find everything just fine! Only one thing: When wake up from sleep, the headphone don't work anymore(speaker fine). Only rebooting makes it back to work.

**Comment by gorquan** [comment]
@wxxsfxyzm Thank you very much! I know this problem exists, but I am still considering whether to fix it. Of course, if you have any good plans, you can tell me

**Comment by gorquan** [comment]
@wxxsfxyzm Hi，wxxsfxyzm. Now that I have fixed the problem of the headphone not working when waking up, you can try the following. If you encounter any problems, please feel free to submit ISSUE

**Comment by romancin** [comment]
How did you boot macOS Big Sur installer? Kernel Panic for me just after starting boot :(

**Comment by gorquan** [comment]
@romancin Please try to delete ThunderBolt related dsdt files and card reader related kext, or you can wait for OC0.6.1 version, I will push it later
